// GENERATED by scripts/generate-staff-directory.mjs — do not hand-edit.
// Regenerate with: node --env-file=.env.local scripts/generate-staff-directory.mjs
//
// No plaintext login code is stored here, only a per-record salt and a peppered scrypt hash of
// it (see src/lib/staff-directory.ts). Reviews are the ones actually submitted for Teachers' Day;
// see that script's source for notes on the (few) editorial choices made converting them.

export interface StaffCredential {
  id: string;
  name: string;
  dept: string;
  avatar_url: string | null;
  salt: string;
  hash: string;
}

export interface ReviewSeed {
  student_alias: string;
  rating: number;
  comment: string;
  tags: string[];
  created_at: string;
}

export const STAFF: StaffCredential[] = [
  { id: "DIST-M8UP", name: "Dr. P. Yogesh", dept: "Information Science & Technology", avatar_url: null, salt: "5455c5af6dee88bb11b374a150c02e6e", hash: "3106c0d28f926822ebd029eef6214145b68748c53c47515a7f40c67ddfb1544504cbc11f12a788c93d97a18acd573c3d4708a2e8e11af0c119d653f6251af79d" },
];

export const REVIEWS: Record<string, ReviewSeed[]> = {
  "DIST-M8UP": [
    { student_alias: "Anonymous student", rating: 5, comment: "Your lectures and interactions between those lectures make us knowledgeable in both technical and non-technical aspects of life.", tags: ["supportive"], created_at: "2026-09-05T09:00:00.000Z" },
  ],
};
